baseURL = "https://mattdanhall.com/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
languageCode = "en-gb"
title = "Matthew D. Hall"
theme = "hugo-theme-console"
canonifyURLs = "true"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  # titleCutting = true

  # animateStyle = "animated zoomIn fast"

  custom_css = ["css/custom.css"]

  [[params.navlinks]]
  name = "CV/"
  url = "CV.pdf"

  [[params.navlinks]]
  name = "gitlab/"
  url = "https://gitlab.com/mattdanhall"

  [[params.navlinks]]
  name = "publications/"
  url = "publications/"

  [[params.navlinks]]
  name = "radio/"
  url = "radio/"