baseURL = "http://mattdanhall.gitlab.io/"
languageCode = "en-us"
title = "Matthew D. Hall"
theme = "hugo-theme-console"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  # titleCutting = true

  # animateStyle = "animated zoomIn fast"

  custom_css = ["css/custom.css"]

  #[[params.navlinks]]
  #name = "CV/"
  #url = "Academic_CV.pdf"

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "publications/"
  url = "publications/"

  [[params.navlinks]]
  name = "radio/"
  url = "radio/"