baseURL = "https://mattdanhall.com/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
languageCode = "en-gb"
title = "mattdanhall.com"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  # titleCutting = true

  custom_css = ["css/console.css"]

  [[params.navlinks]]
  name = "CV/"
  url = "CV.pdf"

  [[params.navlinks]]
  name = "gitlab/"
  url = "https://gitlab.com/mattdanhall"

  [[params.navlinks]]
  name = "publications/"
  url = "publications/"

  [[params.navlinks]]
  name = "projects/"
  url = "projects/"

  [[params.navlinks]]
  name = "radio/"
  url = "radio/"